language: python
python:
- 2.7.8
- 2.7
- 3.3
- 3.4
- 3.5
- nightly
install:
- travis_retry pip install .[all]
- travis_retry pip install codecov
script:
- coverage run -m unittest discover -s tests  -p '*_test.py'
after_success:
- if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then codecov; fi
matrix:
  allow_failures:
  - python: nightly
deploy:
  provider: pypi
  user: thedumptruck
  password:
    secure: Jo7L4I4aQAew407YvBu362YRWoWsUfaM2dnMAeaG1K9lQhJZAoXThZ9hz1uNXoUrMrIvHfrFEUJ9LeoHHNAdGBmpThmE1n2+FmQcY3/mNekX/kiqGB1Dunj4e+Jr1TCTnuE3q3oQU91/rYDjH5CfAJLFAuTFxOaqaMwQFI45j7SLFGQhqOw1A/6BHwd/8K4YqDVtbH47J6bISYmGdTtEHeYeYwOx/swBC5tE6ri4E1oTFYSw5xAni/fzNX7n0N7dhplOg4C340oArvRop4HwuX5dEuaLaYSXRlibzRrba5lFboWz07gJE9WP6fuicNZ5/hSFCzcNZL/p4D/03NKCTxRzGSsob+AR0vVfFEJ1ugqgDnxpoXMlpQq4E6s+OoqFEVZ7oSPkuV8WLUEWlSQdWRIplGvfcJK/5hUi96BebWC4/5X+yaH7/U9/w7mSaJcfpGHv1503aNffeUPIVTVdZkOpyZ5TzfqCwiLWrvLcBuvlo4F/gMyKS96e8eNtPjgH1CzRXymvmeHqUn5jJiP9yYSNI4kPhypwtWCpgPttLbbLIIZmroply8MdVyIcabO/qHNIZQL9ZjPeFCQMHOaHtZXReusHFxRXZ1Jrbd2vTEjmxyclgVJLB336cAsuvy0Xe0T2rxxXCk/pYFqcpzTDOSpkhhFCPYXMyU8Y/haWTTM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: thedumptruck/airflow-contrib
